set(SDL2_COMMON_SOURCES
	Submodules/SDL/src/atomic/SDL_atomic.c
	Submodules/SDL/src/atomic/SDL_spinlock.c
	Submodules/SDL/src/audio/dummy/SDL_dummyaudio.c
	Submodules/SDL/src/audio/SDL_audio.c
	Submodules/SDL/src/audio/SDL_audiocvt.c
	Submodules/SDL/src/audio/SDL_audiodev.c
	Submodules/SDL/src/audio/SDL_audiotypecvt.c
	Submodules/SDL/src/audio/SDL_mixer.c
	Submodules/SDL/src/audio/SDL_wave.c
	Submodules/SDL/src/audio/SDL_mixer.c
	Submodules/SDL/src/cpuinfo/SDL_cpuinfo.c
	Submodules/SDL/src/events/SDL_clipboardevents.c
	Submodules/SDL/src/events/SDL_displayevents.c
	Submodules/SDL/src/events/SDL_dropevents.c
	Submodules/SDL/src/events/SDL_events.c
	Submodules/SDL/src/events/SDL_gesture.c
	Submodules/SDL/src/events/SDL_keyboard.c
	Submodules/SDL/src/events/SDL_mouse.c
	Submodules/SDL/src/events/SDL_quit.c
	Submodules/SDL/src/events/SDL_touch.c
	Submodules/SDL/src/events/SDL_windowevents.c
	Submodules/SDL/src/file/SDL_rwops.c
	Submodules/SDL/src/haptic/SDL_haptic.c
	Submodules/SDL/src/hidapi/SDL_hidapi.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_gamecube.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_luna.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_ps4.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_ps5.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_rumble.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_shield.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_stadia.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_steam.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_switch.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_xbox360.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_xbox360w.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapi_xboxone.c
	Submodules/SDL/src/joystick/hidapi/SDL_hidapijoystick.c
	Submodules/SDL/src/joystick/virtual/SDL_virtualjoystick.c
	Submodules/SDL/src/joystick/controller_type.c
	Submodules/SDL/src/joystick/SDL_gamecontroller.c
	Submodules/SDL/src/joystick/SDL_joystick.c
	Submodules/SDL/src/render/software/SDL_blendfillrect.c
	Submodules/SDL/src/render/software/SDL_blendline.c
	Submodules/SDL/src/render/software/SDL_blendpoint.c
	Submodules/SDL/src/render/software/SDL_drawline.c
	Submodules/SDL/src/render/software/SDL_drawpoint.c
	Submodules/SDL/src/render/software/SDL_render_sw.c
	Submodules/SDL/src/render/software/SDL_rotate.c
	Submodules/SDL/src/render/software/SDL_triangle.c
	Submodules/SDL/src/render/SDL_render.c
	Submodules/SDL/src/render/SDL_yuv_sw.c
	Submodules/SDL/src/sensor/dummy/SDL_dummysensor.c
	Submodules/SDL/src/sensor/SDL_sensor.c
	Submodules/SDL/src/stdlib/SDL_crc32.c
	Submodules/SDL/src/stdlib/SDL_getenv.c
	Submodules/SDL/src/stdlib/SDL_iconv.c
	Submodules/SDL/src/stdlib/SDL_malloc.c
	Submodules/SDL/src/stdlib/SDL_memcpy.c
	Submodules/SDL/src/stdlib/SDL_memset.c
	Submodules/SDL/src/stdlib/SDL_qsort.c
	Submodules/SDL/src/stdlib/SDL_stdlib.c
	Submodules/SDL/src/stdlib/SDL_string.c
	Submodules/SDL/src/stdlib/SDL_strtokr.c
	Submodules/SDL/src/thread/SDL_thread.c
	Submodules/SDL/src/timer/SDL_timer.c
	Submodules/SDL/src/video/dummy/SDL_nullevents.c
	Submodules/SDL/src/video/dummy/SDL_nullframebuffer.c
	Submodules/SDL/src/video/dummy/SDL_nullvideo.c
	Submodules/SDL/src/video/yuv2rgb/yuv_rgb.c
	Submodules/SDL/src/video/SDL_blit_0.c
	Submodules/SDL/src/video/SDL_blit_1.c
	Submodules/SDL/src/video/SDL_blit_A.c
	Submodules/SDL/src/video/SDL_blit_auto.c
	Submodules/SDL/src/video/SDL_blit_copy.c
	Submodules/SDL/src/video/SDL_blit_N.c
	Submodules/SDL/src/video/SDL_blit_slow.c
	Submodules/SDL/src/video/SDL_blit.c
	Submodules/SDL/src/video/SDL_bmp.c
	Submodules/SDL/src/video/SDL_clipboard.c
	Submodules/SDL/src/video/SDL_egl.c
	Submodules/SDL/src/video/SDL_fillrect.c
	Submodules/SDL/src/video/SDL_pixels.c
	Submodules/SDL/src/video/SDL_rect.c
	Submodules/SDL/src/video/SDL_RLEaccel.c
	Submodules/SDL/src/video/SDL_shape.c
	Submodules/SDL/src/video/SDL_stretch.c
	Submodules/SDL/src/video/SDL_surface.c
	Submodules/SDL/src/video/SDL_video.c
	Submodules/SDL/src/video/SDL_vulkan_utils.c
	Submodules/SDL/src/video/SDL_yuv.c
	Submodules/SDL/src/SDL_assert.c
	Submodules/SDL/src/SDL_dataqueue.c
	Submodules/SDL/src/SDL_error.c
	Submodules/SDL/src/SDL_guid.c
	Submodules/SDL/src/SDL_hints.c
	Submodules/SDL/src/SDL_list.c
	Submodules/SDL/src/SDL_log.c
	Submodules/SDL/src/SDL_utils.c
	Submodules/SDL/src/SDL.c
	)

set(SDL2_APPLE_SOURCES
	Submodules/SDL/src/audio/coreaudio/SDL_coreaudio.m
	Submodules/SDL/src/audio/disk/SDL_diskaudio.c
	Submodules/SDL/src/filesystem/cocoa/SDL_sysfilesystem.m
	Submodules/SDL/src/file/cocoa/SDL_rwopsbundlesupport.m
	Submodules/SDL/src/haptic/darwin/SDL_syshaptic.c
	Submodules/SDL/src/joystick/darwin/SDL_iokitjoystick.c
	Submodules/SDL/src/joystick/iphoneos/SDL_mfijoystick.m
	Submodules/SDL/src/loadso/dlopen/SDL_sysloadso.c
	Submodules/SDL/src/render/metal/SDL_render_metal.m
	Submodules/SDL/src/render/opengles2/SDL_render_gles2.c
	Submodules/SDL/src/render/opengles2/SDL_shaders_gles2.c
	Submodules/SDL/src/render/opengl/SDL_render_gl.c
	Submodules/SDL/src/render/opengl/SDL_shaders_gl.c
	Submodules/SDL/src/thread/pthread/SDL_syscond.c
	Submodules/SDL/src/thread/pthread/SDL_sysmutex.c
	Submodules/SDL/src/thread/pthread/SDL_syssem.c
	Submodules/SDL/src/thread/pthread/SDL_systhread.c
	Submodules/SDL/src/thread/pthread/SDL_systls.c
	Submodules/SDL/src/timer/unix/SDL_systimer.c
	Submodules/SDL/src/video/cocoa/SDL_cocoaclipboard.m
	Submodules/SDL/src/video/cocoa/SDL_cocoaevents.m
	Submodules/SDL/src/video/cocoa/SDL_cocoakeyboard.m
	Submodules/SDL/src/video/cocoa/SDL_cocoamessagebox.m
	Submodules/SDL/src/video/cocoa/SDL_cocoametalview.m
	Submodules/SDL/src/video/cocoa/SDL_cocoamodes.m
	Submodules/SDL/src/video/cocoa/SDL_cocoamouse.m
	Submodules/SDL/src/video/cocoa/SDL_cocoaopengl.m
	Submodules/SDL/src/video/cocoa/SDL_cocoaopengles.m
	Submodules/SDL/src/video/cocoa/SDL_cocoashape.m
	Submodules/SDL/src/video/cocoa/SDL_cocoavideo.m
	Submodules/SDL/src/video/cocoa/SDL_cocoavulkan.m
	Submodules/SDL/src/video/cocoa/SDL_cocoawindow.m
	)
